echo "\n OS and version, release number, kernel version:\n"
echo $(uname -a)"\n"
echo "All available shells:\n"
echo $(cat /etc/shells)"\n"
echo "Computer CPU information like processor type, speed etc:\n"
echo $(more /proc/cpuinfo)"\n"
echo "Memory information:\n"
echo $(more /proc/meminfo)"\n"
echo "Hard disk information like size of hard-disk, cache memory, model etc:\n"
echo $(lsblk)"\n"
echo "File system (Mounted):\n"
echo $(more /proc/mounts)"\n"
